# Generated by Django 5.2.3 on 2025-06-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_management_app', '0002_employee_contact_employee_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
