# Generated by Django 5.2.3 on 2025-06-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_management_app', '0004_alter_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='Not Assigned', max_length=100),
        ),
    ]
